apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapp
  template:
    metadata:
      labels:
        app: pokeapp
    spec:
      containers:
        - name: pokeapp
          image: nginx:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: pokeapp-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: pokeapp-volume
          configMap:
            name: pokeapp-static

---
apiVersion: v1
kind: Service
metadata:
  name: pokeapp-service
spec:
  selector:
    app: pokeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
