apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyecto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proyecto
  template:
    metadata:
      labels:
        app: proyecto
    spec:
      containers:
        - name: proyecto
          image: proyecto:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
