apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
      - name: pokeapi
        image: proyecto:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pokeapi-service
spec:
  selector:
    app: pokeapi
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: NodePort
