apiVersion: v1
kind: Service
metadata:
  name: proyecto-service
spec:
  type: NodePort
  selector:
    app: proyecto
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
